server:
  port: 8082
spring:
  application:
    name: gateway-practice
  cloud:
    gateway:
      routes:
        - id: read_body_route
          predicates:
            - Path=/**
          uri: http://localhost # httpbin.org local
          filters:
            - ReadBodyReactive
#        - id: say_hello_route
#          uri: lb://say-hello
#          predicates:
#            - Path=/hello/**
#          filters:
#            - StripPrefix=1
#            - ElapsedPrint=true
#            - Elapsed
#            - name: Hystrix
#              args:
#                name: slowcmd
#                fallbackUri: forward:/hystrixfallback
#            - name: RequestRateLimiter
#              args:
#                key-resolver: "#{@remoteAddressKeyResolver}"
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 2
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
  redis:
    host: localhost
    port: 6379

logging:
  level:
#    root: debug
    org.springframework.cloud.gateway: debug

eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.60.199:1111/eureka/
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true


#  tomcat:
#    basedir: logs/accesslog
#    accesslog:
#      enabled: true
#      prefix: localhost_access_log.
#      suffix: .log
#      pattern: "%h %l %u %t %r %s %b %D"
#      file-date-format: "yyyy-MM-dd.HH"

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
#        timeout:
#          enabled: false
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
