@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response

lbd -> hotGirl: go making love with me
hotGirl --> lbd : ok,let's start right now
@enduml