server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    evictionIntervalTimerInMs: 4000
    responseCacheUpdateIntervalMs: 3000
    enableSelfPreservation: false

logging:
  level:
    com.netflix.eureka: off
    com.netflix.discovery: off
